# Generated by Django 4.2.6 on 2023-11-10 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_basket_total_product_oldprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(default='notyet', max_length=10),
        ),
    ]
