# Generated by Django 4.2.6 on 2023-11-10 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.AddField(
            model_name='basket',
            name='size',
            field=models.CharField(default='notyet', max_length=10),
        ),
    ]
